### ISSUE TITLE
Need a better error when someone has already published a page & you hit publish

### ISSUE THREAD

**Issue by cydharrell** [chimecms/chime#324] opened 2015-07-02 21:48 UTC
If two users are reviewing content at the same time, and both hit publish, the second user to publish receives an uninformative error message with no navigation.

**Comment by phae** [comment] 2015-07-02 21:49
#283 might catch this.

**Comment by migurski** [comment] 2015-07-02 22:12
Another example:

```
2015-07-02 22:11:36,692 - chime.view_functions - ERROR - 'git fetch origin 74b5d90' returned exit status 128: fatal: Couldn't find remote ref 74b5d90
fatal: The remote end hung up unexpectedly
Traceback (most recent call last):
 File "/home/ubuntu/chime/chime/view_functions.py", line 432, in decorated_function
   return route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/view_functions.py", line 464, in decorated_function
   return route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/view_functions.py", line 520, in decorated_function
   response = route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/views.py", line 809, in branch_save
   c2 = repo_functions.save_working_file(repo, path, message, commit.hexsha, master_name)
 File "/home/ubuntu/chime/chime/repo_functions.py", line 503, in save_working_file
   sync_with_default_and_upstream_branches(clone, sync_branch_name)
 File "/home/ubuntu/chime/chime/repo_functions.py", line 468, in sync_with_default_and_upstream_branches
   clone.git.fetch('origin', sync_branch_name)
 File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 227, in <lambda>
   return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 456, in _call_process
   return self.execute(call, **_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 377, in execute
   raise GitCommandError(command, status, stderr_value)
GitCommandError: 'git fetch origin 74b5d90' returned exit status 128: fatal: Couldn't find remote ref 74b5d90
fatal: The remote end hung up unexpectedly

Request info:
<Request 'http://springfield-admin.chimecms.org/tree/74b5d90/save/categories/parks-recreation/parks/springfield-park/index.markdown' [POST]>
```

**Comment by tmaybe** [comment] 2015-07-02 22:39
See also #316

**Comment by norrishung** [comment] 2015-07-06 21:01
Duplicate of #349

**Closed** 2015-07-06 21:02 UTC
Labels: bug, duplicate
